FROM ubuntu:22.04
# designed to avoid the newer Boost issue hit in newer os with newer Boost
# where the build fails inside boost::geometry::wkt(...) during make

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV PATH="/usr/local/bin:${PATH}"

# Basic system deps
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    swig \
    pkg-config \
    curl \
    wget \
    ca-certificates \
    software-properties-common \
    libboost-dev \
    libboost-serialization-dev \
    libgdal-dev \
    gdal-bin \
    libbz2-dev \
    libexpat1-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    python-is-python3 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# Clone FMM
RUN git clone https://github.com/cyang-kth/fmm.git

WORKDIR /opt/fmm

# orginal:
# # Build and install C++ binaries + Python module
# RUN mkdir build && cd build && \
#     cmake .. && \
#     make -j"$(nproc)" && \
#     make install

# tring this flag to maybe make it faster?
# Build and install C++ binaries + Python module
RUN mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j"$(nproc)" && \
    make install

# Install Python bindings into system Python
# commented out as this causes issues during install, so pivoting to CLI instead
# WORKDIR /opt/fmm/python
# RUN pip3 install --no-cache-dir .

# Make sure installed binaries are on PATH
# ENV PATH="/usr/local/bin:${PATH}"

WORKDIR /workspace

CMD ["/bin/bash"]